# Generated by Django 6.1 on 2026-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('education_level', models.CharField(max_length=80)),
                ('province', models.CharField(max_length=120)),
                ('field_of_study', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('coverage', models.TextField(blank=True)),
                ('required_documents', models.TextField(blank=True)),
                ('application_deadline', models.CharField(blank=True, max_length=255)),
                ('application_process', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('collected_by', models.CharField(blank=True, max_length=150)),
                ('date_collected', models.DateField(blank=True, null=True)),
                ('min_marks', models.PositiveSmallIntegerField(blank=True, help_text='Minimum percentage if the scheme states one; otherwise empty.', null=True)),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['name'],
            },
        ),
    ]
