# Generated by Django 6.1 on 2026-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('sector', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('programs', models.TextField(blank=True)),
                ('admission_criteria', models.TextField(blank=True)),
                ('entry_tests', models.CharField(blank=True, max_length=255)),
                ('merit_formula', models.TextField(blank=True)),
                ('admission_intake', models.CharField(blank=True, max_length=255)),
                ('scholarships', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('collected_by', models.CharField(blank=True, max_length=150)),
                ('date_collected', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
    ]
