# Generated by Django 6.1 on 2026-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(max_length=80)),
                ('required_subjects', models.JSONField(blank=True, default=list)),
                ('preferred_levels', models.JSONField(blank=True, default=list)),
                ('interest_tags', models.JSONField(blank=True, default=list)),
                ('market', models.PositiveSmallIntegerField(default=5)),
                ('future', models.PositiveSmallIntegerField(default=5)),
                ('demand_label', models.CharField(blank=True, max_length=80)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('short_desc', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('learn', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('careers', models.JSONField(blank=True, default=list)),
                ('min_background', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
