# Generated by Django 6.1 on 2026-09-03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicProfile',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='level',
            new_name='education_level',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Pre-Engineering', 'Pre-Engineering'),
                    ('Pre-Medical', 'Pre-Medical'),
                    ('ICS', 'ICS'),
                    ('Commerce', 'Commerce'),
                    ('Arts / Humanities', 'Arts / Humanities'),
                    ('Other', 'Other'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Matric', 'Matric'),
                    ('O-Level', 'O-Level'),
                    ('Intermediate', 'Intermediate'),
                    ('A-Level', 'A-Level'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assessment',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'User Assessment',
                'verbose_name_plural': 'User Assessments',
            },
        ),
    ]
