# Generated by Django 6.1 on 2026-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicprofile',
            options={'verbose_name': 'Academic Profile', 'verbose_name_plural': 'Academic Profiles'},
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
    ]
