from datetime import date

from django.core.management.base import BaseCommand

from universities.models import University

UNIVERSITIES = [
    {
        'name': 'Lahore University of Management Sciences (LUMS)',
        'website': 'https://lums.edu.pk',
        'sector': 'Private',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'Computer Science, Software Engineering',
        'admission_criteria': 'SAT/LCAT score; A-Level or FSc Pre-Engineering/ICS',
        'entry_tests': 'LCAT / SAT',
        'merit_formula': 'Holistic evaluation of academic record, test scores, and application',
        'admission_intake': 'Fall',
        'scholarships': 'National Outreach Programme (need-based), merit scholarships',
        'contact': 'admissions@lums.edu.pk',
        'source_url': 'https://admission.lums.edu.pk/undergraduate-admissions',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 25),
    },
    {
        'name': 'National University of Sciences and Technology (NUST)',
        'website': 'https://nust.edu.pk',
        'sector': 'Public',
        'city': 'Islamabad',
        'province': 'Islamabad',
        'programs': 'BE/BS Engineering (Electrical, Mechanical, Civil, Computer Science, Software Engineering)',
        'admission_criteria': 'Minimum 60% marks in both SSC and HSSC',
        'entry_tests': 'NUST Entry Test (NET)',
        'merit_formula': 'NET 75% + HSSC/FSc 15% + SSC/Matric 10%',
        'admission_intake': 'Typically September / Fall (NET sessions)',
        'scholarships': 'Need-based scholarships, NUST merit scholarships',
        'contact': 'admissions@nust.edu.pk',
        'source_url': 'https://nust.edu.pk/admissions/undergraduates/',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 26),
    },
    {
        'name': 'University of Engineering and Technology (UET) Lahore',
        'website': 'https://uet.edu.pk',
        'sector': 'Public',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'BSc Engineering (Electrical, Mechanical, Civil, Chemical, Computer)',
        'admission_criteria': 'FSc Pre-Engineering (or equivalent) with minimum 60% marks',
        'entry_tests': 'ECAT',
        'merit_formula': 'Matric 17% + FSc 50% + ECAT 33%',
        'admission_intake': 'Fall',
        'scholarships': 'UET Lahore merit and need-based scholarships; HEC / PEEF',
        'contact': 'Via admissions.uet.edu.pk online portal',
        'source_url': 'https://admission.uet.edu.pk',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 26),
    },
    {
        'name': 'University of Engineering and Technology (UET) Taxila',
        'website': 'https://uettaxila.edu.pk',
        'sector': 'Public',
        'city': 'Taxila',
        'province': 'Punjab',
        'programs': 'BSc Engineering (Electrical, Mechanical, Civil, Computer)',
        'admission_criteria': 'FSc Pre-Engineering (or equivalent) with minimum 60% marks',
        'entry_tests': 'ECAT',
        'merit_formula': 'Merit list follows UET Lahore pattern (Matric 17% + FSc 50% + ECAT 33%)',
        'admission_intake': 'Fall',
        'scholarships': 'Merit and need-based scholarships; HEC / PEEF',
        'contact': 'admissions@uettaxila.edu.pk',
        'source_url': 'https://uettaxila.edu.pk',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Ghulam Ishaq Khan Institute of Engineering Sciences and Technology (GIKI)',
        'website': 'https://www.giki.edu.pk',
        'sector': 'Private',
        'city': 'Topi',
        'province': 'Khyber Pakhtunkhwa',
        'programs': 'Engineering (Mechanical, Electrical, Computer Engineering, Computer Science)',
        'admission_criteria': 'HSSC / A-Level (or equivalent) with strong Mathematics and Physics',
        'entry_tests': 'GIKI Admission Test',
        'merit_formula': 'GIKI Admission Test + academic record (as per current prospectus)',
        'admission_intake': 'Fall',
        'scholarships': 'Merit scholarships, financial assistance / need-based aid',
        'contact': 'admissions@giki.edu.pk',
        'source_url': 'https://giki.edu.pk/admissions/',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'NED University of Engineering and Technology',
        'website': 'https://www.neduet.edu.pk',
        'sector': 'Public',
        'city': 'Karachi',
        'province': 'Sindh',
        'programs': 'Civil, Mechanical, Electrical, Computer, Software Engineering',
        'admission_criteria': '60% in HSC Part I (for pre-admission); Pre-Engineering / equivalent',
        'entry_tests': 'NED Entry Test',
        'merit_formula': 'As per NED undergraduate admission policy (HSC + entry test)',
        'admission_intake': 'Fall',
        'scholarships': 'Merit and need-based; HEC scholarships',
        'contact': 'registrar@neduet.edu.pk',
        'source_url': 'https://www.neduet.edu.pk/admission',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Pakistan Institute of Engineering and Applied Sciences (PIEAS)',
        'website': 'https://www.pieas.edu.pk',
        'sector': 'Public',
        'city': 'Nilore',
        'province': 'Islamabad',
        'programs': 'Engineering, Computer Science, Applied Sciences',
        'admission_criteria': 'Minimum 60% in SSC and HSSC (Pre-Engineering / equivalent)',
        'entry_tests': 'PIEAS Entry Test',
        'merit_formula': 'PIEAS Test + academic record (as per current advertisement)',
        'admission_intake': 'Fall',
        'scholarships': 'Stipend / scholarship schemes for selected programs; HEC',
        'contact': 'admissions@pieas.edu.pk',
        'source_url': 'https://admissions.pieas.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'COMSATS University Islamabad',
        'website': 'https://www.comsats.edu.pk',
        'sector': 'Public',
        'city': 'Islamabad',
        'province': 'Islamabad',
        'programs': 'Computer Science, Software Engineering, Electrical Engineering, Data Science',
        'admission_criteria': 'Intermediate / equivalent as per program (typically 50–60% minimum)',
        'entry_tests': 'NTS NAT / COMSATS Test (NTS)',
        'merit_formula': 'Academic record + NTS/COMSATS test (campus-wise policy)',
        'admission_intake': 'Fall / Spring',
        'scholarships': 'Merit scholarships, HEC need-based, PEEF (eligible campuses)',
        'contact': 'admissions@comsats.edu.pk',
        'source_url': 'https://admissions.comsats.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'FAST National University of Computer and Emerging Sciences (FAST-NUCES)',
        'website': 'https://www.nu.edu.pk',
        'sector': 'Private',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'BS Computer Science, BS Software Engineering, BS Artificial Intelligence, BS Data Science',
        'admission_criteria': 'Intermediate / equivalent with required subjects for computing programs',
        'entry_tests': 'NU Entry Test / NTS',
        'merit_formula': 'Entry test + intermediate marks (as per FAST admission policy)',
        'admission_intake': 'Fall / Spring',
        'scholarships': 'Merit scholarships, financial assistance',
        'contact': 'admissions@nu.edu.pk',
        'source_url': 'https://www.nu.edu.pk/Admissions',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Air University',
        'website': 'https://www.au.edu.pk',
        'sector': 'Public',
        'city': 'Islamabad',
        'province': 'Islamabad',
        'programs': 'Computer Science, Software Engineering, Electrical Engineering, Aviation-related programs',
        'admission_criteria': 'Intermediate / equivalent as per program eligibility',
        'entry_tests': 'Air University Entry Test / NTS (as applicable)',
        'merit_formula': 'Academic record + entry test (as per current prospectus)',
        'admission_intake': 'Fall / Spring',
        'scholarships': 'Merit and need-based; HEC',
        'contact': 'admissions@au.edu.pk',
        'source_url': 'https://www.au.edu.pk/Pages/Admission/Admission.aspx',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Information Technology University (ITU) Lahore',
        'website': 'https://itu.edu.pk',
        'sector': 'Public',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'Computer Science, Electrical Engineering, Management & Technology',
        'admission_criteria': 'Intermediate / equivalent meeting program-specific minimums',
        'entry_tests': 'ITU Admission Test / SAT (as applicable)',
        'merit_formula': 'Test + academic record (as per ITU undergraduate policy)',
        'admission_intake': 'Fall',
        'scholarships': 'Merit and need-based financial aid',
        'contact': 'admissions@itu.edu.pk',
        'source_url': 'https://itu.edu.pk/admissions/',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'King Edward Medical University (KEMU)',
        'website': 'https://kemu.edu.pk',
        'sector': 'Public',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'MBBS, BDS, Allied Health Sciences',
        'admission_criteria': 'FSc Pre-Medical (or equivalent) as per PMC/UHS rules',
        'entry_tests': 'MDCAT',
        'merit_formula': 'As per UHS / PMC merit policy (MDCAT + FSc + Matric)',
        'admission_intake': 'Fall (as notified by UHS/PMC)',
        'scholarships': 'HEC need-based, PEEF, government merit scholarships',
        'contact': 'info@kemu.edu.pk',
        'source_url': 'https://kemu.edu.pk',
        'collected_by': 'Qandeel Fatima',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'University of Health Sciences (UHS) Lahore',
        'website': 'https://www.uhs.edu.pk',
        'sector': 'Public',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'MBBS, BDS (affiliating / admitting body for medical colleges in Punjab)',
        'admission_criteria': 'FSc Pre-Medical (or equivalent) per PMC regulations',
        'entry_tests': 'MDCAT',
        'merit_formula': 'UHS/PMC notified formula (typically MDCAT + FSc + Matric)',
        'admission_intake': 'As per PMC / provincial schedule',
        'scholarships': 'Government / HEC / PEEF (via colleges)',
        'contact': 'info@uhs.edu.pk',
        'source_url': 'https://www.uhs.edu.pk',
        'collected_by': 'Qandeel Fatima',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Dow University of Health Sciences (DUHS)',
        'website': 'https://www.duhs.edu.pk',
        'sector': 'Public',
        'city': 'Karachi',
        'province': 'Sindh',
        'programs': 'MBBS, BDS, Nursing, Allied Health, Pharmacy',
        'admission_criteria': 'FSc Pre-Medical (or equivalent) per PMC / university rules',
        'entry_tests': 'MDCAT',
        'merit_formula': 'As per Sindh / DUHS admission policy (MDCAT + academics)',
        'admission_intake': 'Fall (as notified)',
        'scholarships': 'Need-based and merit; HEC',
        'contact': 'admissions@duhs.edu.pk',
        'source_url': 'https://www.duhs.edu.pk',
        'collected_by': 'Qandeel Fatima',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Khyber Medical University (KMU)',
        'website': 'https://kmu.edu.pk',
        'sector': 'Public',
        'city': 'Peshawar',
        'province': 'Khyber Pakhtunkhwa',
        'programs': 'MBBS, BDS, Allied Health, Public Health',
        'admission_criteria': 'FSc Pre-Medical (or equivalent) per PMC rules',
        'entry_tests': 'MDCAT',
        'merit_formula': 'As per KMU / PMC merit policy',
        'admission_intake': 'Fall (as notified)',
        'scholarships': 'HEC, provincial need-based / merit',
        'contact': 'info@kmu.edu.pk',
        'source_url': 'https://kmu.edu.pk',
        'collected_by': 'Qandeel Fatima',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Allama Iqbal Medical College (AIMC)',
        'website': 'https://aimc.edu.pk',
        'sector': 'Public',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'MBBS, Allied Health',
        'admission_criteria': 'FSc Pre-Medical (or equivalent) via UHS / PMC',
        'entry_tests': 'MDCAT',
        'merit_formula': 'UHS merit formula (MDCAT + FSc + Matric)',
        'admission_intake': 'As per UHS schedule',
        'scholarships': 'PEEF, HEC, government scholarships',
        'contact': 'Via UHS admission portal',
        'source_url': 'https://aimc.edu.pk',
        'collected_by': 'Qandeel Fatima',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Shifa Tameer-e-Millat University',
        'website': 'https://stmu.edu.pk',
        'sector': 'Private',
        'city': 'Islamabad',
        'province': 'Islamabad',
        'programs': 'MBBS, BDS, Nursing, Allied Health',
        'admission_criteria': 'FSc Pre-Medical (or equivalent) per PMC rules',
        'entry_tests': 'MDCAT',
        'merit_formula': 'MDCAT + academic record (as per Shifa / PMC policy)',
        'admission_intake': 'Fall',
        'scholarships': 'Need-based / merit financial aid',
        'contact': 'admissions@stmu.edu.pk',
        'source_url': 'https://stmu.edu.pk',
        'collected_by': 'Qandeel Fatima',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Rawalpindi Medical University (RMU)',
        'website': 'https://rmur.edu.pk',
        'sector': 'Public',
        'city': 'Rawalpindi',
        'province': 'Punjab',
        'programs': 'MBBS, Allied Health Sciences',
        'admission_criteria': 'FSc Pre-Medical (or equivalent) via UHS / PMC',
        'entry_tests': 'MDCAT',
        'merit_formula': 'UHS merit formula (MDCAT + FSc + Matric)',
        'admission_intake': 'As per UHS schedule',
        'scholarships': 'PEEF, HEC, government scholarships',
        'contact': 'info@rmur.edu.pk',
        'source_url': 'https://rmur.edu.pk',
        'collected_by': 'Qandeel Fatima',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Quaid-i-Azam University (QAU)',
        'website': 'https://qau.edu.pk',
        'sector': 'Public',
        'city': 'Islamabad',
        'province': 'Islamabad',
        'programs': 'Natural Sciences, Social Sciences, Biological Sciences, Computer Science',
        'admission_criteria': 'Intermediate / equivalent with program-specific subject requirements',
        'entry_tests': 'QAU / departmental admission test (as applicable)',
        'merit_formula': 'Academic record + test/interview where required',
        'admission_intake': 'Fall / Spring (program-wise)',
        'scholarships': 'HEC need-based, merit scholarships',
        'contact': 'registrar@qau.edu.pk',
        'source_url': 'https://qau.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'University of the Punjab',
        'website': 'https://pu.edu.pk',
        'sector': 'Public',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'Sciences, Social Sciences, Business, IT, Law, Arts',
        'admission_criteria': 'Intermediate / equivalent; merit lists published by department/college',
        'entry_tests': 'PU admission test where required; otherwise merit-based',
        'merit_formula': 'Primarily intermediate / equivalent marks (program-wise)',
        'admission_intake': 'Fall',
        'scholarships': 'PEEF, HEC, PU merit/need scholarships',
        'contact': 'info@pu.edu.pk',
        'source_url': 'https://pu.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'University of Karachi',
        'website': 'https://uok.edu.pk',
        'sector': 'Public',
        'city': 'Karachi',
        'province': 'Sindh',
        'programs': 'Sciences, Social Sciences, Business, Computer Science, Arts',
        'admission_criteria': 'Intermediate / equivalent as per faculty eligibility',
        'entry_tests': 'KU admission / entry test where applicable',
        'merit_formula': 'Academic merit + test where required',
        'admission_intake': 'Fall',
        'scholarships': 'HEC, university need-based / merit',
        'contact': 'info@uok.edu.pk',
        'source_url': 'https://uok.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Government College University (GCU) Lahore',
        'website': 'https://gcu.edu.pk',
        'sector': 'Public',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'Sciences, Arts, Social Sciences, Computer Science',
        'admission_criteria': 'Intermediate / equivalent; program-wise merit',
        'entry_tests': 'GCU admission test where applicable',
        'merit_formula': 'Academic record + test (program-wise)',
        'admission_intake': 'Fall',
        'scholarships': 'PEEF, HEC, GCU merit scholarships',
        'contact': 'info@gcu.edu.pk',
        'source_url': 'https://gcu.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'University of Peshawar',
        'website': 'https://www.uop.edu.pk',
        'sector': 'Public',
        'city': 'Peshawar',
        'province': 'Khyber Pakhtunkhwa',
        'programs': 'Sciences, Social Sciences, Management, Computer Science',
        'admission_criteria': 'Intermediate / equivalent as per department',
        'entry_tests': 'University / departmental test where required',
        'merit_formula': 'Academic merit + test where required',
        'admission_intake': 'Fall',
        'scholarships': 'HEC, provincial scholarships',
        'contact': 'registrar@uop.edu.pk',
        'source_url': 'https://www.uop.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'University of Sindh',
        'website': 'https://usindh.edu.pk',
        'sector': 'Public',
        'city': 'Jamshoro',
        'province': 'Sindh',
        'programs': 'Sciences, Social Sciences, Arts, Business, IT',
        'admission_criteria': 'Intermediate / equivalent as per faculty',
        'entry_tests': 'University admission process / test where applicable',
        'merit_formula': 'Academic merit (program-wise)',
        'admission_intake': 'Fall',
        'scholarships': 'HEC, provincial / university aid',
        'contact': 'info@usindh.edu.pk',
        'source_url': 'https://usindh.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'University of Agriculture Faisalabad (UAF)',
        'website': 'https://uaf.edu.pk',
        'sector': 'Public',
        'city': 'Faisalabad',
        'province': 'Punjab',
        'programs': 'Agriculture, Food Sciences, Veterinary, Computer Science, Engineering-related programs',
        'admission_criteria': 'Intermediate / equivalent with required science subjects',
        'entry_tests': 'UAF entry / merit as per prospectus',
        'merit_formula': 'Academic record + entry criteria (program-wise)',
        'admission_intake': 'Fall',
        'scholarships': 'PEEF, HEC, UAF merit/need',
        'contact': 'admissions@uaf.edu.pk',
        'source_url': 'https://uaf.edu.pk',
        'collected_by': 'Alisha Javed',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'Institute of Business Administration (IBA) Karachi',
        'website': 'https://www.iba.edu.pk',
        'sector': 'Public',
        'city': 'Karachi',
        'province': 'Sindh',
        'programs': 'BBA, BS Computer Science, Economics, Social Sciences',
        'admission_criteria': 'Intermediate / A-Level / equivalent meeting IBA minimums',
        'entry_tests': 'IBA Aptitude Test / SAT',
        'merit_formula': 'Aptitude test + academic record + interview (as applicable)',
        'admission_intake': 'Fall / Spring',
        'scholarships': 'Need-based financial aid, merit scholarships',
        'contact': 'admissions@iba.edu.pk',
        'source_url': 'https://admissions.iba.edu.pk',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'National University of Modern Languages (NUML)',
        'website': 'https://www.numl.edu.pk',
        'sector': 'Public',
        'city': 'Islamabad',
        'province': 'Islamabad',
        'programs': 'Languages, Social Sciences, Management, Computer Science, Engineering (selected campuses)',
        'admission_criteria': 'Intermediate / equivalent as per program',
        'entry_tests': 'NUML entry test where required',
        'merit_formula': 'Academic record + test (program-wise)',
        'admission_intake': 'Fall / Spring',
        'scholarships': 'HEC, NUML merit/need',
        'contact': 'admissions@numl.edu.pk',
        'source_url': 'https://www.numl.edu.pk',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 28),
    },
    {
        'name': 'University of Central Punjab (UCP)',
        'website': 'https://www.ucp.edu.pk',
        'sector': 'Private',
        'city': 'Lahore',
        'province': 'Punjab',
        'programs': 'Computer Science, Engineering, Business, Law, Social Sciences',
        'admission_criteria': 'Intermediate / equivalent as per faculty eligibility',
        'entry_tests': 'UCP admission test / NTS (as applicable)',
        'merit_formula': 'Academic record + admission test (program-wise)',
        'admission_intake': 'Fall / Spring',
        'scholarships': 'Merit scholarships, need-based financial aid',
        'contact': 'admissions@ucp.edu.pk',
        'source_url': 'https://www.ucp.edu.pk/admissions/',
        'collected_by': 'Hafsa Qamar',
        'date_collected': date(2024, 8, 28),
    },
]


class Command(BaseCommand):
    help = 'Insert spreadsheet university records into the database'

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for row in UNIVERSITIES:
            _, was_created = University.objects.update_or_create(
                name=row['name'],
                defaults=row,
            )
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(
            f'Seeded universities: {created} created, {updated} updated, total {University.objects.count()}'
        ))
