/* ---------- DATA ---------- */
const SUBJECTS = ['Mathematics','Physics','Chemistry','Biology','Computer Science','Accounting','English','Economics','Statistics'];

let FIELDS = [
  { id:1, name:'Software Engineering', category:'Computer Science',
    requiredSubjects:['Mathematics','Computer Science','Physics'], preferredLevels:['Intermediate','A-Level'],
    interestTags:['problem-solving','technology','computers','creating','innovation','cs-it-ai','engineering'],
    market:9, future:9, demandLabel:'Very High Demand', duration:'4 Years',
    desc:'Design, develop and build software solutions that solve real-world problems.',
    about:'Software Engineering applies engineering principles to large-scale software. Strong demand in Pakistan IT export and remote work.',
    learn:['Programming & Algorithms','Data Structures','Databases','Software Design','Web Technologies'],
    skills:['Problem Solving','Programming','System Design','Teamwork'],
    careers:['Software Engineer','Full Stack Developer','DevOps Engineer','QA Engineer'],
    minBackground:['Pre-Engineering','ICS'] },
  { id:2, name:'Data Science', category:'Computer Science',
    requiredSubjects:['Mathematics','Computer Science','Statistics'], preferredLevels:['Intermediate','A-Level'],
    interestTags:['analyzing-data','problem-solving','research','technology','computers','cs-it-ai'],
    market:9, future:10, demandLabel:'Very High Demand', duration:'4 Years',
    desc:'Extract insight and predictive value from data using statistics and programming.',
    about:'Growing demand as Pakistani companies adopt data-driven decisions.',
    learn:['Statistics','Machine Learning','Python','Data Visualization'],
    skills:['Statistics','Python','Critical Thinking'],
    careers:['Data Analyst','Data Scientist','ML Engineer'],
    minBackground:['Pre-Engineering','ICS'] },
  { id:3, name:'Artificial Intelligence', category:'Computer Science',
    requiredSubjects:['Mathematics','Computer Science','Physics'], preferredLevels:['Intermediate','A-Level'],
    interestTags:['technology','research','innovation','problem-solving','computers','cs-it-ai'],
    market:9, future:10, demandLabel:'Very High Demand', duration:'4 Years',
    desc:'Build intelligent systems that learn, reason and make decisions.',
    about:'Extremely high future demand globally and in Pakistan.',
    learn:['Machine Learning','Neural Networks','Python','Mathematics'],
    skills:['Python','ML','Research'],
    careers:['AI Engineer','ML Researcher'],
    minBackground:['Pre-Engineering','ICS'] },
  { id:4, name:'Cyber Security', category:'Computer Science',
    requiredSubjects:['Mathematics','Computer Science'], preferredLevels:['Intermediate','A-Level'],
    interestTags:['technology','problem-solving','computers','detail','cs-it-ai'],
    market:8, future:9, demandLabel:'High Demand', duration:'4 Years',
    desc:'Protect systems, networks and data from digital attacks.',
    about:'Rising demand with digital transformation in Pakistan.',
    learn:['Networking','Cryptography','Ethical Hacking'],
    skills:['Networking','Security Analysis'],
    careers:['Security Analyst','Penetration Tester'],
    minBackground:['Pre-Engineering','ICS'] },
  { id:5, name:'Business Administration', category:'Business',
    requiredSubjects:['Accounting','English','Economics'], preferredLevels:['Intermediate','A-Level'],
    interestTags:['leading','helping-people','analyzing-data','high-salary','office','business','entrepreneur'],
    market:7, future:7, demandLabel:'Growing Demand', duration:'4 Years',
    desc:'Management, finance, marketing and operations.',
    about:'Broad, stable demand; strong entrepreneurship pathway.',
    learn:['Management','Marketing','Accounting','Economics'],
    skills:['Leadership','Communication','Strategic Thinking'],
    careers:['Management Trainee','Marketing Executive','Entrepreneur'],
    minBackground:['Commerce','Any'] },
  { id:6, name:'Medicine (MBBS)', category:'Medical',
    requiredSubjects:['Biology','Chemistry','Physics'], preferredLevels:['Intermediate','A-Level'],
    interestTags:['helping-people','research','detail','medicine','biology'],
    market:8, future:8, demandLabel:'Stable High Prestige', duration:'5+ Years',
    desc:'Diagnose, treat and prevent disease.',
    about:'Requires Pre-Medical and MDCAT. Long study path with strong social impact.',
    learn:['Anatomy','Physiology','Pathology','Pharmacology'],
    skills:['Empathy','Decision-making','Stamina'],
    careers:['Physician','Surgeon','Medical Officer'],
    minBackground:['Pre-Medical'] },
  { id:7, name:'Electrical Engineering', category:'Engineering',
    requiredSubjects:['Mathematics','Physics','Chemistry'], preferredLevels:['Intermediate','A-Level'],
    interestTags:['problem-solving','technology','creating','detail','engineering'],
    market:7, future:7, demandLabel:'Steady Demand', duration:'4 Years',
    desc:'Design systems that use electricity and electronics.',
    about:'Steady demand across power, telecom and manufacturing.',
    learn:['Circuit Analysis','Electronics','Power Systems'],
    skills:['Mathematical Modelling','Circuit Design'],
    careers:['Electrical Engineer','Power Systems Engineer'],
    minBackground:['Pre-Engineering'] },
  { id:8, name:'Psychology', category:'Social Sciences',
    requiredSubjects:['English','Biology'], preferredLevels:['Intermediate','A-Level'],
    interestTags:['helping-people','research','analyzing-data','social-sciences'],
    market:6, future:7, demandLabel:'Growing Demand', duration:'4 Years',
    desc:'Scientific study of mind and behaviour.',
    about:'Growing awareness of mental health expands demand.',
    learn:['Developmental Psychology','Cognitive Psychology','Research Methods'],
    skills:['Active Listening','Empathy','Research'],
    careers:['Clinical Psychologist','Counsellor','HR Specialist'],
    minBackground:['Any'] },
];

let UNIS = [];
let SCHOLS = [];

/* Recommendation questionnaire — same 10 questions as the database */
let QUESTIONS = [
  { id:1, text:'Which activities do you enjoy the most?', type:'multi', min:2, max:3, hint:'Select 2 or 3 options',
    options:[
      {l:'Solving complex problems / puzzles', t:'problem-solving'},
      {l:'Creating or designing things', t:'creating'},
      {l:'Helping and guiding people', t:'helping-people'},
      {l:'Analyzing data and finding patterns', t:'analyzing-data'},
      {l:'Leading teams and organizing work', t:'leading'},
      {l:'Working with technology and computers', t:'technology'},
      {l:'Researching and discovering new knowledge', t:'research'},
    ]},
  { id:2, text:'What kind of work environment do you prefer?', type:'single', min:1, max:1, hint:'Select one option',
    options:[
      {l:'Working mostly with technology and computers', t:'technology'},
      {l:'Working closely with people (patients, clients, students)', t:'helping-people'},
      {l:'Working outdoors or in the field', t:'outdoors'},
      {l:'Working in a lab or research environment', t:'research'},
      {l:'Working in an office / corporate setting', t:'office'},
    ]},
  { id:3, text:'How important is a high salary for you?', type:'single', min:1, max:1, hint:'Select one option',
    options:[
      {l:'Extremely important', t:'high-salary'},
      {l:'Important but not the top priority', t:'salary'},
      {l:'Moderate importance', t:'balanced-life'},
      {l:'Not very important', t:'impact-first'},
    ]},
  { id:4, text:'Do you prefer working independently or in a team?', type:'single', min:1, max:1, hint:'Select one option',
    options:[
      {l:'Mostly independently', t:'independent'},
      {l:'Balance of both', t:'balanced-team'},
      {l:'Mostly in a team', t:'team'},
    ]},
  { id:5, text:'Which subjects did you enjoy the most?', type:'multi', min:2, max:3, hint:'Select 2 or 3 subjects',
    options:[
      {l:'Mathematics', t:'math'},
      {l:'Physics', t:'physics'},
      {l:'Chemistry', t:'chemistry'},
      {l:'Biology', t:'biology'},
      {l:'Computer Science / ICT', t:'computers'},
      {l:'Accounting / Commerce', t:'commerce'},
      {l:'English / Languages', t:'languages'},
      {l:'Arts / Design', t:'creating'},
    ]},
  { id:6, text:'What is your strongest skill?', type:'single', min:1, max:1, hint:'Select one option',
    options:[
      {l:'Logical thinking & problem solving', t:'problem-solving'},
      {l:'Creativity & innovation', t:'innovation'},
      {l:'Communication & interpersonal skills', t:'helping-people'},
      {l:'Attention to detail & accuracy', t:'detail'},
      {l:'Leadership & decision making', t:'leading'},
    ]},
  { id:7, text:'What motivates you the most in a career?', type:'single', min:1, max:1, hint:'Select one option',
    options:[
      {l:'Making a positive impact on society', t:'helping-people'},
      {l:'High earning potential', t:'high-salary'},
      {l:'Innovation and creating new things', t:'innovation'},
      {l:'Job security and stability', t:'security'},
      {l:'Prestige and recognition', t:'prestige'},
    ]},
  { id:8, text:'Are you interested in research and continuous learning?', type:'single', min:1, max:1, hint:'Select one option',
    options:[
      {l:'Yes, I love research and learning new things', t:'research'},
      {l:'Moderately interested', t:'practical'},
      {l:'I prefer practical and applied work', t:'practical'},
    ]},
  { id:9, text:'Preferred work style after graduation', type:'single', min:1, max:1, hint:'Select one option',
    options:[
      {l:'Technical / specialized expert', t:'technology'},
      {l:'Managerial / leadership role', t:'leading'},
      {l:'Entrepreneur / start my own business', t:'entrepreneur'},
      {l:'Helping profession (doctor, teacher, counselor, etc.)', t:'helping-people'},
    ]},
  { id:10, text:'Which broad area interests you the most right now?', type:'multi', min:2, max:3, hint:'Select 2 or 3 areas',
    options:[
      {l:'Computer Science / IT / AI', t:'cs-it-ai'},
      {l:'Engineering', t:'engineering'},
      {l:'Medicine / Health Sciences', t:'medicine'},
      {l:'Business / Management / Finance', t:'business'},
      {l:'Natural Sciences / Research', t:'natural-sciences'},
      {l:'Social Sciences / Law / Humanities', t:'social-sciences'},
      {l:'Design / Creative fields', t:'design'},
    ]},
];
